apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: learn
data:
  NODE_ENV: "production"
  MAX_ACTIVE_COURSES: "5"
  R2_BUCKET_NAME: "napskytech"
  R2_PUBLIC_URL: "https://r2.napskytech.com"
  REDIS_URL: "redis://redis:6379"
