apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: learn
data:
  NODE_ENV: "production"
  MAX_ACTIVE_COURSES: "5"
  R2_BUCKET_NAME: "napskytech"
  R2_PUBLIC_URL: "https://pub-7a86a28e5e554c329214c3b1b424673c.r2.dev"
  REDIS_URL: "redis://redis:6379"
